name: Run Cypress Tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

permissions:
    contents: write

jobs:
    deployed-e2e:
        runs-on: ubuntu-latest
        name: Test Deployed Application

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            - name: Install Dependencies
              run: npm ci

            - name: Run Cypress Tests
              uses: cypress-io/github-action@v6
              env:
                  CYPRESS_ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
                  CYPRESS_ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
                  CYPRESS_BASE_URL: https://beer-pong-tournament.vercel.app
                  VITE_SERVER_ADDRESS: https://beer-pong-tournament-backend.onrender.com
              with:
                  browser: electron
                  spec: cypress/e2e/beer-pong-tournament/deployed.cy.js

            - name: Upload Cypress Artifacts
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: cypress-artifacts
                  path: |
                      cypress/screenshots
                      cypress/videos

    local-e2e:
        runs-on: ubuntu-latest
        name: Test Local Application

        env:
            CYPRESS_BASE_URL: http://127.0.0.1:5173
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            VITE_SERVER_ADDRESS: http://127.0.0.1:8000

        steps:
            - name: Checkout Frontend
              uses: actions/checkout@v4

            - name: Clone Backend
              uses: actions/checkout@v4
              with:
                  repository: StackOverflowIsBetterThanAnyAI/beer-pong-tournament-backend
                  path: backend

            - name: Install Dependencies - Frontend
              run: npm ci

            - name: Start Frontend
              run: npm start -- --host 127.0.0.1 > frontend.log 2>&1 &
              shell: bash

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11

            - name: Install Dependencies - Backend
              working-directory: ./backend
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run Migrations
              working-directory: ./backend
              run: python manage.py migrate

            - name: Start Backend
              working-directory: ./backend
              run: |
                  python manage.py runserver 127.0.0.1:8000 > backend.log 2>&1 &
                  sleep 10
                  echo "===== backend.log output ====="
                  cat backend.log
              shell: bash

            - name: Wait for servers
              run: npx wait-on --timeout 60000 http://127.0.0.1:5173 http://127.0.0.1:8000

            - name: Run Cypress Tests
              uses: cypress-io/github-action@v6
              env:
                  CYPRESS_ADMIN_PASSWORD: admin1234
                  CYPRESS_ADMIN_USERNAME: admin
              with:
                  browser: electron
                  spec: cypress/e2e/beer-pong-tournament/local.cy.js

            - name: Upload Cypress Artifacts
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: cypress-artifacts
                  path: |
                      cypress/screenshots
                      cypress/videos

            - name: Upload Backend Log
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: backend-log
                  path: ./backend/backend.log

            - name: Upload Frontend Log
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: frontend-log
                  path: frontend.log
