name: Run Cypress Tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

permissions:
    contents: write

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            - name: Install Dependencies
              run: npm ci

            - name: Build App
              run: npm run build

            - name: Run Cypress Tests
              uses: cypress-io/github-action@v6
              with:
                  start: npm start
                  wait-on: 'http://127.0.0.1:5173'
                  browser: electron

            - name: Upload Cypress Artifacts
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: cypress-artifacts
                  path: |
                      cypress/screenshots
                      cypress/videos
